### ISSUE TITLE
MultiMap code doesn't compile on Scala 2.12

### ISSUE THREAD

**Issue by SethTisue** [scala/collection-strawman#320]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2383/consoleFull:

```
[collection-strawman] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/collection-strawman-e4fa658d51a8957ca9964d417e9dc1c0c37fd810/collections-contrib/src/test/scala/strawman/collection/MultiMapTest.scala:53: missing parameter type for expanded function
[collection-strawman] [error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[collection-strawman] [error] Expected type was: ?
[collection-strawman] [error]       MultiMap("a" -> 1, "b" -> 1, "b" -> 2).map { case (k, v) => (k.toUpperCase, v) }
[collection-strawman] [error]                                                  ^
[collection-strawman] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/collection-strawman-e4fa658d51a8957ca9964d417e9dc1c0c37fd810/collections-contrib/src/test/scala/strawman/collection/MultiMapTest.scala:53: value toUpperCase is not a member of Any
[collection-strawman] [error]       MultiMap("a" -> 1, "b" -> 1, "b" -> 2).map { case (k, v) => (k.toUpperCase, v) }
[collection-strawman] [error]                                                                      ^
[collection-strawman] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/collection-strawman-e4fa658d51a8957ca9964d417e9dc1c0c37fd810/collections-contrib/src/test/scala/strawman/collection/MultiMapTest.scala:57: missing parameter type for expanded function
[collection-strawman] [error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[collection-strawman] [error] Expected type was: ?
[collection-strawman] [error]       MultiMap("a" -> true, "b" -> true).map { case (_, v) => 1 -> v }
[collection-strawman] [error]                                              ^
[collection-strawman] [error] three errors found
```

(is it still even a goal for the strawman to compile on 2.12...?)

**Comment by julienrf** [comment]
Indeed, I didn’t check that… We have additional type annotations in other tests to make them compile with 2.12. I’m really looking forward to remove them ASAP (see #113).

I don’t think we should try to support 2.12.

**Comment by SethTisue** [comment]
I have dropped this repo from the 2.12 community build
