### ISSUE TITLE
Seq.fold no longer exists

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#537]
```
scala> Seq(1).fold(0)(_ + _)
              ^
       error: value fold is not a member of scala.collection.immutable.Seq[Int]
```

works in 2.11
