### ISSUE TITLE
Java interop: List<T>.drop doesn't return List<T> in javac's view

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#536]
This Java code compiles in 2.11, and also used to work at some point in strawman:
```
  public static String list(List<String> x) {
    List<String> y = x.drop(2);
    return y.head();
  }
```

Currently, it fails to compile with
```
error: incompatible types: LinearSeq cannot be converted to List<String>
```

Probably has something to do with bounds / erasure of type parameters, or generic signatures.

When fixed, look for `TODO-newColl` in `test/files/pos/javaReadsSigs/fromjava.java` and remove the cast.

**Comment by szeiger** [comment]
`drop` was overridden in 2.12. We can do the same in 2.13 for selected methods where this is necessary but we need to determine how much Java compatibility we want to provide.

**Comment by lrytz** [comment]
I think we can just close this one. The situation is not any worse than in 2.12 per se, methods that are not overridden in have the same issue in 2.12. For example

```
$ cat Test.java
import scala.collection.immutable.*;

public class Test {
  public static void main(String[] args) {
    List<String> l = null;
    List<String> ll = l.dropRight(0);
  }
}
$ javac -cp ~/scala/scala-2.12/lib/scala-library.jar Test.java
Test.java:6: error: incompatible types: LinearSeqOptimized cannot be converted to List<String>
    List<String> ll = l.dropRight(0);
                                 ^
1 error
$
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6540
